export enum MeldFaan {
    SEAT_WIND_PONG = 'SEAT_WIND_PONG',
    PREVAILING_WIND_PONG = 'PREVAILING_WIND_PONG',
    RED_DRAGON_PONG = 'RED_DRAGON_PONG',
    GREEN_DRAGON_PONG = 'GREEN_DRAGON_PONG',
    WHITE_DRAGON_PONG = 'WHITE_DRAGON_PONG'
}