export enum SpecialWinningHandType {
    THIRTEEN_ORPHANS = 'THIRTEEN_ORPHANS',
    LESSER_HONORS_KNITTED = 'LESSER_HONORS_KNITTED',
    GREATER_HONORS_KNITTED = 'GREATER_HONORS_KNITTED',
    CUSTOM = 'CUSTOM'
}